# Generated by Django 2.2.3 on 2019-07-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.IntegerField()),
                ('town', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('building', models.CharField(max_length=256)),
                ('appartement', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=16)),
                ('import_id', models.ForeignKey(db_column='import_id', on_delete=django.db.models.deletion.CASCADE, to='imports.Import')),
                ('relatives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imports.Citizen')),
            ],
            options={
                'unique_together': {('import_id', 'citizen_id')},
            },
        ),
    ]
