# Generated by Django 2.2.3 on 2019-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='relatives',
        ),
        migrations.AddField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(related_name='_citizen_relatives_+', to='imports.Citizen'),
        ),
    ]
