# Generated by Django 2.2.3 on 2019-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_auto_20190719_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(to='imports.Citizen'),
        ),
    ]
