# Generated by Django 2.2.3 on 2019-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_auto_20190719_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(related_name='_citizen_relatives_+', to='imports.Citizen'),
        ),
    ]
